In [13]:
import pandas as pd
import os

In [14]:
file_path = r"V:\dunwei\MACE\dataset\tabular_data\static_dynamic_data/"
save_data_path = r"V:\dunwei\MACE\dataset\tabular_data\static_dynamic_data/"

In [15]:
if not os.path.exists(save_data_path):
    os.makedirs(save_data_path)
    print(f"Created directory: {save_data_path}")
else:
    print(f"{save_data_path} already exists.")

V:\dunwei\MACE\dataset\tabular_data\static_dynamic_data/ already exists.

In [16]:
mode = 1
"""
1: Missing value
2: Non-missing value (non use)
"""
if mode == 1:
    data = pd.read_csv(file_path + "MACE_static_dynamic_founder_askna_mr_missing_data.csv")
elif mode == 2:
    data = pd.read_csv(file_path + "combine_tabular_data_non_missing_value.csv")
    print('No create file')
display(data)

,research_id,count_v_ar,count_copd,smoke_try,count_dm,male,founder_proba_1,askna_mr_proba_1,mace
0,MACE001,0.0,0.0,1.0,0.0,1,0.121087,0.005500,0
1,MACE001,0.0,0.0,1.0,0.0,1,0.100348,0.005576,0
2,MACE001,0.0,0.0,1.0,0.0,1,0.071083,0.001369,0
3,MACE001,0.0,0.0,1.0,0.0,1,0.032122,0.001150,0
4,MACE001,0.0,0.0,1.0,0.0,1,0.059235,0.001128,0
...,...,...,...,...,...,...,...,...,...
198021,MACE524,0.0,0.0,0.0,0.0,0,0.171240,0.003639,0
198022,MACE524,0.0,0.0,0.0,0.0,0,0.085280,0.002059,0
198023,MACE524,0.0,0.0,0.0,0.0,0,0.111515,0.006535,0
198024,MACE524,0.0,0.0,0.0,0.0,0,0.125780,0.004351,0
198025,MACE524,0.0,0.0,0.0,0.0,0,0.077930,0.004092,0

In [17]:
header = data.columns.tolist()
data_arr = data.values
display(data_arr)

array([['MACE001', 0.0, 0.0, ..., 0.121086955, 0.005499723, 0],
       ['MACE001', 0.0, 0.0, ..., 0.100347824, 0.00557599, 0],
       ['MACE001', 0.0, 0.0, ..., 0.07108261, 0.0013691774, 0],
       ...,
       ['MACE524', 0.0, 0.0, ..., 0.111515, 0.0065348456, 0],
       ['MACE524', 0.0, 0.0, ..., 0.12578, 0.0043506795, 0],
       ['MACE524', 0.0, 0.0, ..., 0.07793, 0.0040921527, 0]],
      shape=(198026, 9), dtype=object)

In [18]:
h = []
p = []
for i in range(data_arr.shape[0]):
    if data_arr[i, -1] == 0:
        h.append(data_arr[i, :])
    elif data_arr[i, -1] == 1:
        p.append(data_arr[i, :])

h_df = pd.DataFrame(h, columns=header)
p_df = pd.DataFrame(p, columns=header)
display(h_df)
display(p_df)

if mode == 1:
    h_df.to_csv(save_data_path + "missing_data/static_dynamic_founder_askna_mr_h_missing_value.csv", index=False)
    p_df.to_csv(save_data_path + "missing_data/static_dynamic_founder_askna_mr_p_missing_value.csv", index=False)
elif mode == 2:
    h_df.to_csv(save_data_path + "non_missing_data/static_dynamic_founder_h_non_missing_value.csv", index=False)
    p_df.to_csv(save_data_path + "non_missing_data/static_dynamic_founder_p_non_missing_value.csv", index=False)

print(f"save path : {save_data_path}")

,research_id,count_v_ar,count_copd,smoke_try,count_dm,male,founder_proba_1,askna_mr_proba_1,mace
0,MACE001,0.0,0.0,1.0,0.0,1,0.121087,0.005500,0
1,MACE001,0.0,0.0,1.0,0.0,1,0.100348,0.005576,0
2,MACE001,0.0,0.0,1.0,0.0,1,0.071083,0.001369,0
3,MACE001,0.0,0.0,1.0,0.0,1,0.032122,0.001150,0
4,MACE001,0.0,0.0,1.0,0.0,1,0.059235,0.001128,0
...,...,...,...,...,...,...,...,...,...
162850,MACE524,0.0,0.0,0.0,0.0,0,0.171240,0.003639,0
162851,MACE524,0.0,0.0,0.0,0.0,0,0.085280,0.002059,0
162852,MACE524,0.0,0.0,0.0,0.0,0,0.111515,0.006535,0
162853,MACE524,0.0,0.0,0.0,0.0,0,0.125780,0.004351,0
162854,MACE524,0.0,0.0,0.0,0.0,0,0.077930,0.004092,0

,research_id,count_v_ar,count_copd,smoke_try,count_dm,male,founder_proba_1,askna_mr_proba_1,mace
0,MACE021,0.0,0.0,0.0,0.0,0,0.544209,0.021790,1
1,MACE021,0.0,0.0,0.0,0.0,0,0.555617,0.021767,1
2,MACE021,0.0,0.0,0.0,0.0,0,0.443083,0.020192,1
3,MACE021,0.0,0.0,0.0,0.0,0,0.523957,0.030242,1
4,MACE021,0.0,0.0,0.0,0.0,0,0.527861,0.009181,1
...,...,...,...,...,...,...,...,...,...
35166,MACE513,0.0,0.0,0.0,1.0,1,0.137271,0.002280,1
35167,MACE513,0.0,0.0,0.0,1.0,1,0.153417,0.004500,1
35168,MACE513,0.0,0.0,0.0,1.0,1,0.054500,0.007938,1
35169,MACE513,0.0,0.0,0.0,1.0,1,0.108583,0.005382,1
35170,MACE513,0.0,0.0,0.0,1.0,1,0.119908,0.001648,1

save path : V:\dunwei\MACE\dataset\tabular_data\static_dynamic_data/