In [88]:
import pandas as pd
import os
import glob

In [ ]:
raw_data_path = r"F:\M143020071\raw_data/"
id_path = r"D:\M143020071\raw_data_result\tabular_data/"
save_data_path = r"D:\M143020071\raw_data_result/"

In [90]:
raw_data = pd.read_csv(os.path.join(raw_data_path, "MACE 資料登錄(新增VT)_killip finial.csv"))
id_corr = pd.read_csv(os.path.join(id_path, "MACE_id_correlation.csv"))
display(id_corr)



print("success")

      Original_ID Transformation_ID
0    414490914181           MACE001
1    534491345995           MACE002
2    584487583289           MACE003
3    354480714133           MACE004
4    364481044155           MACE005
..            ...               ...
519  334472223207           MACE520
520  474468168901           MACE521
521  484552428693           MACE522
522  454552424829           MACE523
523  374552404823           MACE524

[524 rows x 2 columns]

success

In [91]:
h = []
p = []
id_num = '研究編號'
label = 'mace'

for idx, row in raw_data.iterrows():
    if  row[label] == 0:
        h.append(row[id_num])
    elif row[label] == 1:
        p.append(row[id_num])
    else:
        print(f"Error label in row {idx + 1}: {row[label]}, id: {row[id_num]}")

display(p)

[514479622089,
 424506442575,
 394508481351,
 464502429983,
 284502332153,
 384503413279,
 394504051749,
 364504322349,
 374504267135,
 574497822993,
 584498528909,
 504498450169,
 574498375359,
 494494551647,
 574495988181,
 564495997063,
 564496737619,
 534456598453,
 514457658291,
 494452254995,
 454453823727,
 434455080881,
 554446790489,
 424447403439,
 394447250445,
 384443373703,
 424443581805,
 544444755597,
 504472087567,
 404472536063,
 394472703183,
 324473133133,
 464468585321,
 534465247957,
 484465186761,
 484466457219,
 494466436349,
 454466742219,
 434467436441,
 554459305799,
 484459770345,
 604461795879,
 394461774015,
 514461696609,
 554462648579,
 404478209051,
 604479869643,
 504507486925,
 484508477445,
 464501977229,
 354502555225,
 354502921039,
 434504737661,
 494499469031,
 424500182967,
 354500142775,
 514495386309,
 474457178047,
 524457438665,
 394459152333,
 384453412393,
 434454254465,
 464454573743,
 594447993595,
 544448628279,
 544449099375,
 364442750037,
 394442708505,
 434471927207,
 444472797301,
 424471283085,
 354471292033,
 374464005563,
 434464460645,
 364464301347,
 544465927269,
 514459366905,
 474459336931,
 394461132567,
 364460933313,
 474463423993,
 514463244987,
 584556277697,
 564556079299,
 474556436419,
 514556714991,
 554556896417,
 464557487015,
 534557456881,
 624558969781]

In [92]:
h_df = pd.DataFrame(h, columns=['research_ID'])
p_df = pd.DataFrame(p, columns=['research_ID'])
display(h_df)

      research_ID
0    414490914181
1    534491345995
2    584487583289
3    354480714133
4    364481044155
..            ...
429  334472223207
430  474468168901
431  484552428693
432  454552424829
433  374552404823

[434 rows x 1 columns]

In [93]:
h_conversion = []
p_conversion = []
for idx, row in h_df.iterrows():
    for idx2, row2 in id_corr.iterrows():
        if row['research_ID'] == row2['Original_ID']:
            h_conversion.append(row2['Transformation_ID'])
            break
        else:
            pass

for idx, row in p_df.iterrows():
    for idx2, row2 in id_corr.iterrows():
        if row['research_ID'] == row2['Original_ID']:
            p_conversion.append(row2['Transformation_ID'])
            break
        else:
            pass

In [94]:
h_conversion_df = pd.DataFrame(h_conversion, columns=['conversion_ID'])
p_conversion_df = pd.DataFrame(p_conversion, columns=['conversion_ID'])

h_corr_df = pd.concat([h_df, h_conversion_df], axis=1)
p_corr_df = pd.concat([p_df, p_conversion_df], axis=1)
h_corr_df.to_csv(save_data_path + "MACE_h_id.csv", index=False)
p_corr_df.to_csv(save_data_path + "MACE_p_id.csv", index=False)
display(h_corr_df.to_csv)
print(f'file saved in : {save_data_path}')

<bound method NDFrame.to_csv of       research_ID conversion_ID
0    414490914181       MACE001
1    534491345995       MACE002
2    584487583289       MACE003
3    354480714133       MACE004
4    364481044155       MACE005
..            ...           ...
429  334472223207       MACE520
430  474468168901       MACE521
431  484552428693       MACE522
432  454552424829       MACE523
433  374552404823       MACE524

[434 rows x 2 columns]>

file saved in : F:\M143020071\raw_data_result/