In [7]:
import pandas as pd

In [8]:
pre_process_path = r'V:\dunwei\MACE\dataset\pre_process/'
save_data_path = r'V:\dunwei\MACE\dataset\pre_process\five_feature/'
imputed_data_path = r'V:\dunwei\MACE\dataset\reversed/'

In [9]:
feature = ['count_v_ar', 'count_copd', 'smoke_try', 'count_dm', 'male']
research_id = ['Transformation_ID']
label = ['mace']

In [10]:
mode = 1
"""
mode = 1 ---> raw data pre-processing
mode = 2 ---> imputed data pre-processing
"""

'\nmode = 1 ---> raw data pre-processing\nmode = 2 ---> imputed data pre-processing\n'

In [ ]:
raw_data = pd.read_csv(pre_process_path + 'MACE_raw_data.csv')
display(raw_data)

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,MACE001,0,0,0,0,0,0,0,0.0,1,...,99.0,0.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.0,0
1,MACE002,1,0,0,0,0,0,1,1.0,0,...,72.0,0.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.0,0
2,MACE003,0,0,0,0,0,0,0,1.0,0,...,80.0,0.0,NaN,0.787275,NaN,NaN,NaN,NaN,4.0,0
3,MACE004,0,0,0,0,0,0,1,1.0,0,...,86.0,0.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.0,0
4,MACE005,0,0,0,0,0,0,0,0.0,1,...,64.0,0.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0,1,0,0,0,0,0,0.0,1,...,71.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
520,MACE521,0,0,0,0,0,0,0,0.0,1,...,89.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0
521,MACE522,0,0,0,0,0,0,0,0.0,1,...,74.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0
522,MACE523,0,1,0,0,0,0,0,0.0,1,...,77.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0
523,MACE524,0,0,0,0,0,0,0,0.0,1,...,68.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [12]:
if mode == 1:
    print("raw data pre-processing")
    raw_data = pd.read_csv(pre_process_path + "MACE_research_id_transformation.csv")
    raw_data = raw_data[research_id + feature + label]
    display(raw_data)

    H = []
    P = []
    for idx, row in raw_data.iterrows():
        if row['mace'] == 0:
            H.append(row)
        else:
            P.append(row)

    H_df = pd.DataFrame(H).reset_index(drop=True)
    P_df = pd.DataFrame(P).reset_index(drop=True)

    H_df.to_csv(save_data_path + "H.csv", index=False)
    P_df.to_csv(save_data_path + "P.csv", index=False)

elif mode == 2:
    print("imputed data pre-processing")
    imputed_data = pd.read_csv(imputed_data_path + "MACE_imputed_data.csv")
    # 依照編號由小到大排列
    imputed_data['SortKey'] = imputed_data.iloc[:, 0].str.extract(r'(\d+)').astype(int)  # 提取數字部分，轉成整數型別
    imputed_data_sorted = imputed_data.sort_values(by='SortKey')  # 根據數字排序
    imputed_data_sorted = imputed_data_sorted.drop(columns=['SortKey'])  # 刪除輔助排序欄位（可選）
    imputed_data_sorted = imputed_data_sorted.reset_index(drop=True)  # 重設索引

    H = []
    P = []
    for idx, row in imputed_data_sorted.iterrows():
        if row['mace'] == 0:
            H.append(row)
        else:
            P.append(row)

    H_df = pd.DataFrame(H).reset_index(drop=True)
    P_df = pd.DataFrame(P).reset_index(drop=True)

    H_df.to_csv(save_data_path + "H_imputed.csv", index=False)
    P_df.to_csv(save_data_path + "P_imputed.csv", index=False)

else:
    raise ValueError("error mode")

print(f"save_path: {save_data_path}")

raw data pre-processing

    Transformation_ID  count_v_ar  count_copd  smoke_try  count_dm  male  mace
0             MACE001         0.0         0.0        1.0       0.0     1     0
1             MACE002         0.0         0.0        1.0       1.0     1     0
2             MACE003         0.0         0.0        0.0       0.0     0     0
3             MACE004         0.0         0.0        0.0       0.0     1     0
4             MACE005         0.0         0.0        1.0       0.0     1     0
..                ...         ...         ...        ...       ...   ...   ...
519           MACE520         0.0         0.0        1.0       0.0     1     0
520           MACE521         0.0         0.0        0.0       0.0     1     0
521           MACE522         0.0         0.0        1.0       1.0     1     0
522           MACE523         0.0         0.0        0.0       1.0     1     0
523           MACE524         0.0         0.0        0.0       0.0     0     0

[524 rows x 7 columns]

save_path: V:\dunwei\MACE\dataset\pre_process\five_feature/