In [7]:
import pandas as pd
import os

In [8]:
MACE_raw_data_dir = r'V:\dunwei\MACE\dataset\tabular_data/'
save_dir = r'V:\dunwei\MACE\dataset\tabular_data\static_feature/'

In [9]:
if not os.path.exists(save_dir):
    os.makedirs(save_dir)
    print(f"Created directory: {save_dir}")
else:
    print(f"Directory already exists: {save_dir}")

Directory already exists: V:\dunwei\MACE\dataset\tabular_data\static_feature/

In [10]:
research_id = ['Transformation_ID']
feature = ['count_v_ar', 'count_copd', 'smoke_try', 'count_dm', 'male']
label = ['mace']

In [11]:
MACE_raw_data = pd.read_csv(os.path.join(MACE_raw_data_dir, 'MACE_research_id_transformation.csv'))
display(MACE_raw_data)

,Transformation_ID,indate_skna,ID,SEX,outdate_skna,INDEXDATE,acei_use,arb_use,c1_use,c3_use,...,master,PCIdate,SKNAdate1,mace_date2,TIMI,Killip,APACH II,ReMI,arrhythmia,p.s
0,MACE001,2016/12/12,13359.0,M,2016/12/16,2016/12/16,0,0,0,0,...,1.0,2016/12/12,2016/12/13,.,5.0,II,NaN,NaN,NaN,NaN
1,MACE002,2016/12/21,20198.0,M,2016/12/29,2016/12/29,1,0,0,0,...,1.0,2016/12/21,2016/12/22,.,4.0,III,NaN,NaN,NaN,NaN
2,MACE003,2019/11/18,11797.0,F,2019/11/25,2019/11/25,0,0,0,0,...,1.0,2019/11/21,2019/11/21,.,4.0,I,NaN,NaN,NaN,NaN
3,MACE004,2017/9/16,12755.0,M,2017/9/21,2017/9/21,0,0,0,0,...,1.0,2017/9/18,2017/9/18,.,3.0,I,NaN,NaN,NaN,NaN
4,MACE005,2017/10/5,44.0,M,2017/10/10,2017/10/10,0,0,0,0,...,1.0,2017/10/5,2017/10/6,.,4.0,I,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,2023/2/27,NaN,M,2023/3/3,NaN,0,1,0,0,...,NaN,2023/2/26,2023/3/1,NaN,2.0,I,NaN,0.0,0.0,NaN
520,MACE521,2023/3/1,NaN,M,2023/3/6,NaN,0,0,0,0,...,NaN,2023/3/1,2023/3/2,NaN,4.0,I,NaN,0.0,0.0,NaN
521,MACE522,2023/2/21,NaN,M,2023/2/27,NaN,0,0,0,0,...,NaN,2023/2/21,2023/2/22,NaN,7.0,II,NaN,0.0,1.0,NaN
522,MACE523,2023/2/28,NaN,M,2023/3/7,NaN,0,1,0,0,...,NaN,2023/2/28,2023/3/2,NaN,5.0,I,NaN,0.0,1.0,NaN
523,MACE524,2023/3/7,NaN,F,2023/3/13,NaN,0,0,0,0,...,NaN,2023/3/7,2023/3/9,NaN,NaN,I,3.0,0.0,0.0,NaN

In [12]:
MACE_extract_raw_data = MACE_raw_data.loc[:, research_id + feature + label]
display(MACE_extract_raw_data)
MACE_extract_raw_data.to_csv(os.path.join(save_dir, 'MACE_preprocessed_tabular_data_5features.csv'), index=False)

    Transformation_ID  count_v_ar  count_copd  smoke_try  count_dm  male  mace
0             MACE001         0.0         0.0        1.0       0.0     1     0
1             MACE002         0.0         0.0        1.0       1.0     1     0
2             MACE003         0.0         0.0        0.0       0.0     0     0
3             MACE004         0.0         0.0        0.0       0.0     1     0
4             MACE005         0.0         0.0        1.0       0.0     1     0
..                ...         ...         ...        ...       ...   ...   ...
519           MACE520         0.0         0.0        1.0       0.0     1     0
520           MACE521         0.0         0.0        0.0       0.0     1     0
521           MACE522         0.0         0.0        1.0       1.0     1     0
522           MACE523         0.0         0.0        0.0       1.0     1     0
523           MACE524         0.0         0.0        0.0       0.0     0     0

[524 rows x 7 columns]